### PR TITLE
Tiny fix to fix opam build.

### PR DESCRIPTION
**Pull request by bsansouci**

### CODE REVIEW

**Comment by jordwalke** [comment]
Wait doesn't this mean that node will be required to install this package via opam? Isn't there a way to drop the node requirement when installing for opam?

**Comment by bordoley** [comment]
Why does this have to be a makefile step?

**Comment by bsansouci** [comment]
ooh wait this makes node a real dep, not a dev dep... Crap we probably don't want that. I can figure out how to build opam_of_packagejson with rebuild and push it on opam.

**Comment by bordoley** [comment]
can we avoid the hassle by checking in the immutable.install file?

**Comment by bsansouci** [comment]
It worked locally to remove the `.install` from the `.gitignore`, good idea!

**Comment by jordwalke** [comment]
Isn't opam_of_package_json written in OCaml? Is it possible to vendor it, and run it at publish time to generate the opam file, then run it at build time to generate the install?

**Comment by bordoley** [comment]
I'm gonna merge this and attempt another release.

**Pull request merged**
